<?xml version="1.0"?>
<robot  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
        xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
        xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
        xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- sensors -->
	<include filename="$(find youbot_description)/urdf/sensors/hokuyo_urg04_laser.urdf.xacro"/>

	<include filename="$(find youbot_description)/urdf/youbot_base/base.gazebo.xacro" />
	<include filename="$(find youbot_description)/urdf/youbot_base/base.transmission.xacro" />
        
 	<!-- simplified box collision geometry for base -->
  	<property name="base_size_x" value="0.570" />
  	<property name="base_size_y" value="0.360" />
  	<property name="base_size_z" value="0.100" />
	<property name="base_mass" value="22.0" />

	<property name="caster_offset_x" value="0.228"  />  
  	<property name="caster_offset_y" value="0.158"  />  
  	<property name="caster_offset_z" value="-0.034" />
	<property name="caster_mass" value="0.1" />

	<property name="wheel_offset_x" value="0.0"  />  
  	<property name="wheel_offset_y" value="0.0"  />  
  	<property name="wheel_offset_z" value="0.0" />
	<property name="wheel_mass" value="0.4" />

	<property name="wheel_radius" value="0.05" />
	<property name="wheel_length" value="0.005" />
  	
	<property name="caster_joint_damping" value="1.0" />
	<property name="caster_joint_friction" value="1.0" />
	<property name="caster_joint_effort" value="30" />
	<property name="caster_joint_velocity" value="10" />
	<property name="caster_joint_safety_k_velocity" value="10.0" />

	<property name="wheel_joint_damping" value="1.0" />
	<property name="wheel_joint_friction" value="1.0" />
	<property name="wheel_joint_effort" value="30" />
	<property name="wheel_joint_velocity" value="10" />
	<property name="wheel_joint_safety_k_velocity" value="10.0" />

	<xacro:macro name="youbot_base" params="name">
		
		<link name="${name}_footprint">
      			<inertial>
        			<mass value="0.1" />
        			<origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0" />
        			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
                 			iyy="1.0" iyz="0.0" izz="1.0" />
      				</inertial>
      			<visual>
        			<origin xyz="0 0 0" rpy="0 0 0" />
        			<geometry>
          				<box size="0.001 0.001 0.001" />
        			</geometry>
               			<material name="Red" />
      			</visual>
      			<collision>
        			<origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0" />
        			<geometry>
          				<box size="0.001 0.001 0.001" />
        			</geometry>
      			</collision>
    		</link>

    		<joint name="${name}_footprint_joint" type="fixed">
      			<origin xyz="0 0 0" rpy="0 0 0" />
      			<child link="${name}_link" />
      			<parent link="${name}_footprint"/>
    		</joint>

		<link name="${name}_link">
      			<inertial>
        			<mass value="${base_mass}" />
        			<origin xyz="0 0 0" />
        			<inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423"
                 			iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
      				</inertial>
      			<visual>
        			<origin xyz="0 0 0" rpy="0 0 0" />  
        			<geometry>
          				<mesh filename="package://youbot_description/meshes/youbot_base/base.dae"/>
        			</geometry> 
        			<material name="DarkGrey"/>
      			</visual>
      			<collision>
        			<origin xyz="0 0 0" rpy="0 0 0" />
        			<geometry>
          				<!--<box size="${base_size_x} ${base_size_y} ${base_size_z}" />-->
					<mesh filename="package://youbot_description/meshes/youbot_base/base_convex.dae"/>
	       			</geometry>
      			</collision>
    		</link>		

		<!-- base laser front -->
                       
    		<xacro:hokuyo_urg04_laser name="${name}_laser_front" parent="${name}" ros_topic="scan_front" update_rate="10" min_angle="-1.57" max_angle="1.57" >
     			 <origin xyz="0.3 0 -0.03" rpy="0 0 0" />
    		</xacro:hokuyo_urg04_laser>
		
	
	</xacro:macro>

</robot>
